name: CI to Docker Hub

on:
  push:
    tags:
      - v*.*.*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.5

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          platforms: |
            linux/arm64/v8
          build-args: |
            APP_NAME=blrec
            APP_VERSION=${{ github.ref_name }}
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/blrec:latest
            ${{ secrets.DOCKER_HUB_USERNAME }}/blrec:${{ github.ref_name }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
